
# Audio settings
DEFAULT_SAMPLE_RATE = 44100
DEFAULT_BUFFER_SIZE = 1024
DEFAULT_VOLUME = 1.0
DEFAULT_PITCH = 1.0
DEFAULT_REVERB = 0.0

# Audio limits
VOLUME_MIN = 0.0
VOLUME_MAX = 2.0
PITCH_MIN = 0.1
PITCH_MAX = 2.0
REVERB_MIN = 0.0
REVERB_MAX = 2.0  

# Tracking settings
DEFAULT_DETECTION_CONFIDENCE = 0.7
DEFAULT_TRACKING_CONFIDENCE = 0.5  
DEFAULT_MAX_HANDS = 2
DEFAULT_MODEL_COMPLEXITY = 1  

# Camera size 
DEFAULT_CAMERA_WIDTH = 640   
DEFAULT_CAMERA_HEIGHT = 480  

# Hand landmark
THUMB_TIP = 4
INDEX_TIP = 8
MIDDLE_TIP = 12
RING_TIP = 16
PINKY_TIP = 20
WRIST = 0

# Distance ranges for hand
PITCH_DISTANCE_MIN = 30
PITCH_DISTANCE_MAX = 150
REVERB_DISTANCE_MIN = 30
REVERB_DISTANCE_MAX = 150
VOLUME_DISTANCE_MIN = 50
VOLUME_DISTANCE_MAX = 300

# Audio ranges
PITCH_RANGE_MIN = 0.5
PITCH_RANGE_MAX = 2.0
REVERB_RANGE_MIN = 0.0
REVERB_RANGE_MAX = 2.0
VOLUME_RANGE_MIN = 0.0
VOLUME_RANGE_MAX = 2.0

# GUI colors
BACKGROUND_COLOR = "#1e1e1e"
BUTTON_COLOR = "#3a3a3a"
BUTTON_HOVER_COLOR = "#505050"
BUTTON_PRESSED_COLOR = "#2a2a2a"
INPUT_BACKGROUND_COLOR = "#2a2a2a"
TEXT_COLOR = "white"

# File path and naming
TEMP_FILE_PREFIX = "handdj_"
TEMP_FILE_SUFFIX = ".wav"
DEFAULT_AUDIO_FILES = ["testing.mp3", "test_audio.wav", "audio.mp3", "music.mp3"]

# Update intervals (seconds)
PARAMETER_UPDATE_INTERVAL = 0.5
PROGRESS_UPDATE_INTERVAL = 0.1

# Smoothing settings
SMOOTHING_FACTOR = 0.2
VOLUME_SMOOTHING_FACTOR = 0.1
BUFFER_SIZE = 5 