
DEFAULT_SAMPLE_RATE = 44100
DEFAULT_BUFFER_SIZE = 1024
DEFAULT_VOLUME = 1.0
DEFAULT_PITCH = 1.0
DEFAULT_REVERB = 0.0

VOLUME_MIN = 0.0
VOLUME_MAX = 2.0
PITCH_MIN = 0.1
PITCH_MAX = 2.0
REVERB_MIN = 0.0
REVERB_MAX = 2.0

DEFAULT_DETECTION_CONFIDENCE = 0.7
DEFAULT_TRACKING_CONFIDENCE = 0.5
DEFAULT_MAX_HANDS = 2

DEFAULT_CAMERA_WIDTH = 640
DEFAULT_CAMERA_HEIGHT = 480

# mediapipe landmark indices
THUMB_TIP = 4
INDEX_TIP = 8

# pixel distance ranges that map to audio parameter ranges
PITCH_DISTANCE_MIN = 30
PITCH_DISTANCE_MAX = 150
REVERB_DISTANCE_MIN = 30
REVERB_DISTANCE_MAX = 150
VOLUME_DISTANCE_MIN = 50
VOLUME_DISTANCE_MAX = 300

PITCH_RANGE_MIN = 0.5
PITCH_RANGE_MAX = 2.0
REVERB_RANGE_MIN = 0.0
REVERB_RANGE_MAX = 2.0
VOLUME_RANGE_MIN = 0.0
VOLUME_RANGE_MAX = 2.0

BACKGROUND_COLOR = "#1e1e1e"
TEXT_COLOR = "white"

PARAMETER_UPDATE_INTERVAL = 0.5

SMOOTHING_FACTOR = 0.2
# volume uses a lower factor so it feels more responsive to hand movement
VOLUME_SMOOTHING_FACTOR = 0.1
BUFFER_SIZE = 5
